#ifndef LAOOCC_LEXER_TOKEN_H
#define LAOOCC_LEXER_TOKEN_H

#include <stddef.h>

typedef enum lo_token_kind {
    LO_LEXER_TOKEN_INVALID = 0,

    LO_LEXER_TOKEN_EOF,

    LO_LEXER_TOKEN_IDENTIFIER,
    LO_LEXER_TOKEN_NUMBER,
    LO_LEXER_TOKEN_STRING,
    LO_LEXER_TOKEN_CHARACTER,

    LO_LEXER_TOKEN_KW_AUTO,
    LO_LEXER_TOKEN_KW_BREAK,
    LO_LEXER_TOKEN_KW_CASE,
    LO_LEXER_TOKEN_KW_CHAR,
    LO_LEXER_TOKEN_KW_CONST,
    LO_LEXER_TOKEN_KW_CONTINUE,
    LO_LEXER_TOKEN_KW_DEFAULT,
    LO_LEXER_TOKEN_KW_DO,
    LO_LEXER_TOKEN_KW_DOUBLE,
    LO_LEXER_TOKEN_KW_ELSE,
    LO_LEXER_TOKEN_KW_ENUM,
    LO_LEXER_TOKEN_KW_EXTERN,
    LO_LEXER_TOKEN_KW_FLOAT,
    LO_LEXER_TOKEN_KW_FOR,
    LO_LEXER_TOKEN_KW_GOTO,
    LO_LEXER_TOKEN_KW_IF,
    LO_LEXER_TOKEN_KW_INT,
    LO_LEXER_TOKEN_KW_LONG,
    LO_LEXER_TOKEN_KW_REGISTER,
    LO_LEXER_TOKEN_KW_RETURN,
    LO_LEXER_TOKEN_KW_SHORT,
    LO_LEXER_TOKEN_KW_SIGNED,
    LO_LEXER_TOKEN_KW_SIZEOF,
    LO_LEXER_TOKEN_KW_STATIC,
    LO_LEXER_TOKEN_KW_STRUCT,
    LO_LEXER_TOKEN_KW_SWITCH,
    LO_LEXER_TOKEN_KW_TYPEDEF,
    LO_LEXER_TOKEN_KW_UNION,
    LO_LEXER_TOKEN_KW_UNSIGNED,
    LO_LEXER_TOKEN_KW_VOID,
    LO_LEXER_TOKEN_KW_VOLATILE,
    LO_LEXER_TOKEN_KW_WHILE,

    LO_LEXER_TOKEN_PLUS,
    LO_LEXER_TOKEN_MINUS,
    LO_LEXER_TOKEN_STAR,
    LO_LEXER_TOKEN_SLASH,
    LO_LEXER_TOKEN_PERCENT,

    LO_LEXER_TOKEN_AMPERSAND,
    LO_LEXER_TOKEN_PIPE,
    LO_LEXER_TOKEN_CARET,
    LO_LEXER_TOKEN_TILDE,
    LO_LEXER_TOKEN_BANG,

    LO_LEXER_TOKEN_ASSIGN,
    LO_LEXER_TOKEN_EQUAL,
    LO_LEXER_TOKEN_NOT_EQUAL,

    LO_LEXER_TOKEN_LESS,
    LO_LEXER_TOKEN_LESS_EQUAL,
    LO_LEXER_TOKEN_GREATER,
    LO_LEXER_TOKEN_GREATER_EQUAL,

    LO_LEXER_TOKEN_INCREMENT,
    LO_LEXER_TOKEN_DECREMENT,

    LO_LEXER_TOKEN_AND,
    LO_LEXER_TOKEN_OR,

    LO_LEXER_TOKEN_LPAREN,
    LO_LEXER_TOKEN_RPAREN,
    LO_LEXER_TOKEN_LBRACE,
    LO_LEXER_TOKEN_RBRACE,
    LO_LEXER_TOKEN_LBRACKET,
    LO_LEXER_TOKEN_RBRACKET,

    LO_LEXER_TOKEN_COMMA,
    LO_LEXER_TOKEN_DOT,
    LO_LEXER_TOKEN_SEMICOLON,
    LO_LEXER_TOKEN_COLON,
    LO_LEXER_TOKEN_QUESTION,

    LO_LEXER_TOKEN_ARROW
} lo_token_kind;

typedef struct lo_token {
    lo_token_kind kind;
    const char *start;
    size_t length;
    size_t line;
    size_t column;
} lo_token;

const char *lo_token_kind_name(lo_token_kind kind);

#endif
