#ifndef LAOOCC_CORE_STATUS_H
#define LAOOCC_CORE_STATUS_H

typedef enum lo_status {
    LO_STATUS_OK = 0,
    LO_STATUS_ERROR,

    LO_STATUS_INVALID_ARGUMENT,
    LO_STATUS_OUT_OF_MEMORY,
    LO_STATUS_NOT_FOUND,
    LO_STATUS_NOT_IMPLEMENTED,
    LO_STATUS_OVERFLOW,
    LO_STATUS_UNDERFLOW
} lo_status;

#endif /* LAOOCC_CORE_STATUS_H */
